Do not lint ERB in CI (#6938)
We suddenly started getting errors like the following in `release/0.22-stable` and
`release/0.23-stable`.

```
Run ./.github/run_erblint.sh
bundler: failed to load command: erblint (/home/runner/work/decidim/decidim/vendor/bundle/ruby/2.5.0/bin/erblint)
NameError: uninitialized constant BetterHtml::Parser::HtmlError
Did you mean?  HtmlTokenizer
```

Apparently the only way to solve it is upgrading to erblint 0.0.35. That
however, requires a Rubocop upgrade that is too costly.  This will do
the trick since this branch is only meant to receive fixes.